chore: Bump kotlin-gradle-plugin from 1.4.10 to 1.4.20 (#197)
Bumps [kotlin-gradle-plugin](https://github.com/JetBrains/kotlin) from 1.4.10 to 1.4.20.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/JetBrains/kotlin/releases">kotlin-gradle-plugin's releases</a>.</em></p>
<blockquote>
<h2>Kotlin 1.4.20</h2>
<h2>CHANGELOG</h2>
<h3>Android</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-42121"><code>KT-42121</code></a> Deprecate Kotlin Android Extensions compiler plugin</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-42267"><code>KT-42267</code></a> <code>Platform declaration clash</code> error in IDE when using <code>kotlinx.android.parcel.Parcelize</code></li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-42406"><code>KT-42406</code></a> Long or infinite code analysis on simple files modification</li>
</ul>
<h3>Backend. Native</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-27534"><code>KT-27534</code></a> Bridges to Nothing-returning methods have incorrect signature</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-30284"><code>KT-30284</code></a> Native: Nothing? type for expression override and crash</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-36430"><code>KT-36430</code></a> Optimize when with in range cases</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-38787"><code>KT-38787</code></a> Missing optimization for &quot;in range&quot; check</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-39100"><code>KT-39100</code></a> Make Native behaviour of property initialization consistent with JVM</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-39798"><code>KT-39798</code></a> Override equals/hashCode in functional interface wrappers on Native</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-39800"><code>KT-39800</code></a> equals/hashCode on adapted function references on Native</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-41394"><code>KT-41394</code></a> Compilation failed: Backend Internal error: Exception during IR lowering</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-41907"><code>KT-41907</code></a> Framework test segfaults on GC on watchos_x86 compiled with -opt</li>
</ul>
<h3>Compiler</h3>
<h4>New Features</h4>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-21147"><code>KT-21147</code></a> JEP 280: Indify String Concatenation (StringConcatFactory)</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-34178"><code>KT-34178</code></a> Scripts should be able to access imports objects</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-35549"><code>KT-35549</code></a> Support kotlin-android-extensions in JVM IR backend (for use with Jetpack Compose projects)</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-31567"><code>KT-31567</code></a> Support special semantics for underscore-named catch block parameters</li>
</ul>
<h4>Performance Improvements</h4>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-20571"><code>KT-20571</code></a> Coroutines: Reduce number of local variables stored at suspension point</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-28016"><code>KT-28016</code></a> Coroutine state-machines spill/unspill shall be optimized using data-flow analysis</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-33394"><code>KT-33394</code></a> UI freezes triggered by QualifiedExpressionResolver.resolveToPackageOrClassPrefix</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-36814"><code>KT-36814</code></a> Support optimized delegated properties in JVM_IR</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-36829"><code>KT-36829</code></a> Optimize 'in' expressions (operator fun contains) in JVM_IR</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-41741"><code>KT-41741</code></a> NI: &quot;AssertionError: Empty intersection for types&quot; with generic Java collection</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-42195"><code>KT-42195</code></a> NI: prohibitively long compilation time for values of nested data structures with type inference</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-42221"><code>KT-42221</code></a> Native compiler never finishes frontend phase after migrating to Kotlin 1.4.10</li>
</ul>
<h4>Fixes</h4>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-11713"><code>KT-11713</code></a> Refine visibility check for synthetic property with protected setter</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-16222"><code>KT-16222</code></a> Coroutine should be clearing any internal state as soon as possible to avoid memory leaks</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-25519"><code>KT-25519</code></a> Extra inline marks inside suspending function callable reference bytecode</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-33226"><code>KT-33226</code></a> Object INSTANCE field not annotated with NotNull in generated bytecode</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-35495"><code>KT-35495</code></a> FIR: forbid non-Java synthetic properties</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-35651"><code>KT-35651</code></a> Kotlin stdlib has greater resolution priority than jars added via <a href="https://github.com/file">@file</a>:DependsOn annotation</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-35716"><code>KT-35716</code></a> Using <a href="https://github.com/JvmOverloads">@JvmOverloads</a> in <a href="https://github.com/JvmStatic">@JvmStatic</a> functions in interface companion objects causes a ClassFormatError</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/JetBrains/kotlin/blob/v1.4.20/ChangeLog.md">kotlin-gradle-plugin's changelog</a>.</em></p>
<blockquote>
<h2>1.4.20</h2>
<h3>Android</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-42121"><code>KT-42121</code></a> Deprecate Kotlin Android Extensions compiler plugin</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-42267"><code>KT-42267</code></a> <code>Platform declaration clash</code> error in IDE when using <code>kotlinx.android.parcel.Parcelize</code></li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-42406"><code>KT-42406</code></a> Long or infinite code analysis on simple files modification</li>
</ul>
<h3>Backend. Native</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-27534"><code>KT-27534</code></a> Bridges to Nothing-returning methods have incorrect signature</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-30284"><code>KT-30284</code></a> Native: Nothing? type for expression override and crash</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-36430"><code>KT-36430</code></a> Optimize when with in range cases</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-38787"><code>KT-38787</code></a> Missing optimization for &quot;in range&quot; check</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-39100"><code>KT-39100</code></a> Make Native behaviour of property initialization consistent with JVM</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-39798"><code>KT-39798</code></a> Override equals/hashCode in functional interface wrappers on Native</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-39800"><code>KT-39800</code></a> equals/hashCode on adapted function references on Native</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-41394"><code>KT-41394</code></a> Compilation failed: Backend Internal error: Exception during IR lowering</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-41907"><code>KT-41907</code></a> Framework test segfaults on GC on watchos_x86 compiled with -opt</li>
</ul>
<h3>Compiler</h3>
<h4>New Features</h4>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-21147"><code>KT-21147</code></a> JEP 280: Indify String Concatenation (StringConcatFactory)</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-34178"><code>KT-34178</code></a> Scripts should be able to access imports objects</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-35549"><code>KT-35549</code></a> Support kotlin-android-extensions in JVM IR backend (for use with Jetpack Compose projects)</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-31567"><code>KT-31567</code></a> Support special semantics for underscore-named catch block parameters</li>
</ul>
<h4>Performance Improvements</h4>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-20571"><code>KT-20571</code></a> Coroutines: Reduce number of local variables stored at suspension point</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-28016"><code>KT-28016</code></a> Coroutine state-machines spill/unspill shall be optimized using data-flow analysis</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-33394"><code>KT-33394</code></a> UI freezes triggered by QualifiedExpressionResolver.resolveToPackageOrClassPrefix</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-36814"><code>KT-36814</code></a> Support optimized delegated properties in JVM_IR</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-36829"><code>KT-36829</code></a> Optimize 'in' expressions (operator fun contains) in JVM_IR</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-41741"><code>KT-41741</code></a> NI: &quot;AssertionError: Empty intersection for types&quot; with generic Java collection</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-42195"><code>KT-42195</code></a> NI: prohibitively long compilation time for values of nested data structures with type inference</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-42221"><code>KT-42221</code></a> Native compiler never finishes frontend phase after migrating to Kotlin 1.4.10</li>
</ul>
<h4>Fixes</h4>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-11713"><code>KT-11713</code></a> Refine visibility check for synthetic property with protected setter</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-16222"><code>KT-16222</code></a> Coroutine should be clearing any internal state as soon as possible to avoid memory leaks</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-25519"><code>KT-25519</code></a> Extra inline marks inside suspending function callable reference bytecode</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-33226"><code>KT-33226</code></a> Object INSTANCE field not annotated with NotNull in generated bytecode</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-35495"><code>KT-35495</code></a> FIR: forbid non-Java synthetic properties</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-35651"><code>KT-35651</code></a> Kotlin stdlib has greater resolution priority than jars added via <a href="https://github.com/file">@file</a>:DependsOn annotation</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-35716"><code>KT-35716</code></a> Using <a href="https://github.com/JvmOverloads">@JvmOverloads</a> in <a href="https://github.com/JvmStatic">@JvmStatic</a> functions in interface companion objects causes a ClassFormatError</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-35730"><code>KT-35730</code></a> FIR: consider creating fake overrides for objects</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/JetBrains/kotlin/commit/d0c005400b1d2e220e16fea1343e6dd0e074f086"><code>d0c0054</code></a> Update changelog for 1.4.20 release</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/49a7e0068569df3039b22a69ddd31c8839ae82b5"><code>49a7e00</code></a> Run tests AS42 under JDK 11</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/0e75999ce1b77dc2974b8b584aad94e33c76b552"><code>0e75999</code></a> Clean up non failed tests in AS42</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/995df014e391a269c88e7c03ea064b54c2ebb401"><code>995df01</code></a> Don't set KOTLIN_BUNDLED in unit tests in AS42</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/90305141cd8eeaf42c8d8494d2f234096dd037d6"><code>9030514</code></a> Use absolute path to the project in test in AS 4.2</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/8aea0139b049dd8ac450990c4b2493d0333629ca"><code>8aea013</code></a> Fix ClassNotFoundException: org.w3c.dom.ElementTraversal</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/c37d269225c1ff56a24d9fadf1469d5a5ab759d8"><code>c37d269</code></a> Fix compilation</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/53e74af304accd4b6e2d657967a9765f8aebec89"><code>53e74af</code></a> Register DumpUtil if it has not been registered yet in AS42</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/5cc229cfb3ed6691e4d78fa82a247b7dd3c46b53"><code>5cc229c</code></a> Fix compilation in AS 4.2</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/be71a871ae7b79c9291ca5685aec3c335ed731e5"><code>be71a87</code></a> Fix tests for as42.</li>
<li>Additional commits viewable in <a href="https://github.com/JetBrains/kotlin/compare/v1.4.10...v1.4.20">compare view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility score](https://api.dependabot.com/badges/compatibility_score?dependency-name=org.jetbrains.kotlin:kotlin-gradle-plugin&package-manager=gradle&previous-version=1.4.10&new-version=1.4.20)](https://dependabot.com/compatibility-score/?dependency-name=org.jetbrains.kotlin:kotlin-gradle-plugin&package-manager=gradle&previous-version=1.4.10&new-version=1.4.20)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)
- `@dependabot badge me` will comment on this PR with code to add a "Dependabot enabled" badge to your readme

Additionally, you can set the following in the `.dependabot/config.yml` file in this repo:
- Update frequency
- Out-of-range updates (receive only lockfile updates, if desired)
- Security updates (receive only security updates, if desired)



</details>